package olc1.golite.visitor;

import olc1.golite.ast.exp.*;
import olc1.golite.ast.stm.*;

public interface Visitor<T> {
    T visit(Integers.Context ctx);
    T visit(Decimal.Context ctx);
    T visit(Paren.Context ctx);
    T visit(Add.Context ctx);
    T visit(Sub.Context ctx);
    T visit(Mul.Context ctx);
    T visit(Div.Context ctx);
    T visit(Negate.Context ctx);
    T visit(BoolLiteral.Context ctx);
    T visit(StringLiteral.Context ctx);
    T visit(VarRef.Context ctx);
    T visit(Imprimir.Context ctx);
    T visit(Assign.Context ctx);
    T visit(IfNode.Context ctx);
    T visit(Statments.Context ctx);
    T visit(GreaterThan.Context ctx);
    T visit(LessThan.Context ctx);
    T visit(Equals.Context ctx);
    T visit(NotEquals.Context ctx);
    T visit(GreaterEqual.Context ctx);
    T visit(LessEqual.Context ctx);
    T visit(And.Context ctx);
    T visit(Or.Context ctx);
    T visit(Not.Context ctx);
    T visit(Mod.Context ctx);
    T visit(PlusAssign.Context ctx);
    T visit(MinusAssign.Context ctx);
    T visit(ForNode.Context ctx);
    T visit(Increment.Context ctx);
    T visit(Decrement.Context ctx);
    T visit(FmtPrintln.Context ctx);
    T visit(BreakNode.Context ctx);
    T visit(ContinueNode.Context ctx);
    T visit(VarDeclInfer.Context ctx);
    T visit(VarDecl.Context ctx);
    T visit(SliceLiteral.Context ctx);
    T visit(ForRangeNode.Context ctx);
    T visit(RuneLiteral.Context ctx);
    T visit(TypeOfNode.Context ctx);
    T visit(AtoiNode.Context ctx);
    T visit(ParseFloatNode.Context ctx);
    T visit(NilLiteral.Context ctx);
    T visit(BlockNode.Context ctx);
    T visit(SwitchNode.Context ctx);
    T visit(CaseNode.Context ctx);
    T visit(ProgramNode.Context ctx);
    T visit(FunctionDecl.Context ctx);
    T visit(ParameterNode.Context ctx);
    T visit(ReturnNode.Context ctx);
    T visit(FunctionCall.Context ctx);
    T visit(SliceAccess.Context ctx);
    T visit(SliceAssign.Context ctx);
    T visit(LenNode.Context ctx);
    T visit(AppendNode.Context ctx);
    T visit(SlicesIndexNode.Context ctx);
    T visit(StringsJoinNode.Context ctx);
    T visit(MultiSliceLiteral.Context ctx);
    T visit(MultiSliceAccess.Context ctx);
    T visit(MultiSliceAssign.Context ctx);
}
